export const SHEET_NAME = "Sheet 1";

export const emptyExcelHeaderObj = {
        "S.No": '',
        "Title in Google Drive": "",
        "Link to File Location": "",
        "Link to Truncated File Location": "",
        "Title in English": "",
        "Title in Original Script ( Devanagari etc )": "",
        "Sub-Title": "",
        "Author": "",
        "Commentator/ Translator/Editor": "",
        "Language(s)": "",
        "Script": "",
        "Subject/ Descriptor": "",
        "Publisher": "",
        "Edition/Statement": "",
        "Place of Publication": "",
        "Year of Publication": "",
        "No. of Pages": "",
        "ISBN": "",
        "Remarks": "",
        "Commentairies": "",
        "Commentator": "",
        "Series ( KSTS/Kavyamala/Chowkhamba etc": "",
        "Size with Units": "",
        "Size in Bytes": "",
        "Folder Name": "",
    }
    